name: Php Lint
on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php-cs-fixer:
    name: php-cs check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php${{ matrix.php-versions }}
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          tools: composer:v1
          coverage: none
      - name: Install dependencies
        run: composer i
      - name: Run coding standards check
        run: composer run cs:check
